services:
  - type: web
    name: kisan-mitra-backend
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free

  - type: web
    name: kisan-mitra-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://kisan-mitra-backend.onrender.com/api/*
