import React, { useState } from 'react';
import { Calendar, CheckSquare, Square, Clock, AlertCircle, ArrowUpRight, Sparkles, Filter } from 'lucide-react';

export default function DecisionTimeline({ activeField }) {
  const [timeline, setTimeline] = useState([
    {
      id: 1,
      week: "Week 1 (Current)",
      title: "Foliar Spray: Mancozeb 75% WP (Indofil M-45)",
      category: "Spray",
      details: "Apply 600g in 200L water per acre before expected heavy rainfall on Day 2 to prevent Early Blight spore dispersion.",
      priority: "Urgent",
      completed: false
    },
    {
      id: 2,
      week: "Week 1 (Current)",
      title: "Adjust Drip Irrigation Schedule to 45 Mins Daily",
      category: "Irrigation",
      details: "Soil moisture is currently at 34%. Reduce drip cycle due to incoming 48hr rain forecast.",
      priority: "Recommended",
      completed: false
    },
    {
      id: 3,
      week: "Week 2",
      title: "Optimal Harvest Window: Harvest in 3 Days",
      category: "Harvest",
      details: "Target Mandi: Nashik APMC Market. Expected mandi price: ₹2,750/quintal (+12.2% price gain).",
      priority: "Urgent",
      completed: false
    },
    {
      id: 4,
      week: "Week 3",
      title: "Post-Harvest Fertigation & Soil Drenching",
      category: "Fertilizer",
      details: "Apply 15 kg Urea per acre via fertigation and drench root zone with humic acid (2L/acre).",
      priority: "Normal",
      completed: false
    },
    {
      id: 5,
      week: "Week 4",
      title: "Field Scouting & Crop Rotation Preparation",
      category: "Inspection",
      details: "Inspect lower foliage canopy for sucking pests (whiteflies/thrips) and prepare soil for next crop cycle.",
      priority: "Normal",
      completed: false
    }
  ]);

  const toggleTask = (id) => {
    setTimeline(prev => prev.map(item => item.id === id ? { ...item, completed: !item.completed } : item));
  };

  const getCategoryBadge = (cat) => {
    switch (cat) {
      case 'Spray': return 'bg-rose-500/10 text-rose-400 border-rose-500/30';
      case 'Irrigation': return 'bg-sky-500/10 text-sky-400 border-sky-500/30';
      case 'Harvest': return 'bg-amber-500/10 text-amber-400 border-amber-500/30';
      case 'Fertilizer': return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30';
      default: return 'bg-slate-800 text-slate-300 border-slate-700';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-slate-900/60 backdrop-blur-xl border border-slate-800 p-6 rounded-2xl flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-100 flex items-center gap-2">
            <Calendar className="w-6 h-6 text-emerald-400" />
            Week-by-Week Farm Decision Timeline
          </h2>
          <p className="text-sm text-slate-400">
            Dynamic calendar roadmap generated by the Multi-Agent Orchestrator based on growth stage, weather & mandi trends.
          </p>
        </div>
        <div className="flex items-center gap-2 bg-slate-950 px-3 py-2 rounded-xl border border-slate-800 text-xs font-semibold text-slate-300">
          <Clock className="w-4 h-4 text-emerald-400" />
          Growth Stage: <span className="text-emerald-400">{activeField?.growth_stage || 'Fruiting'}</span>
        </div>
      </div>

      {/* Timeline List */}
      <div className="bg-slate-900/60 backdrop-blur-xl border border-slate-800 p-6 rounded-2xl space-y-6 relative">
        <div className="absolute left-9 top-12 bottom-12 w-0.5 bg-slate-800 hidden sm:block"></div>

        {timeline.map((item) => (
          <div key={item.id} className="flex flex-col sm:flex-row items-start gap-4 relative">
            {/* Timeline Circle */}
            <button
              onClick={() => toggleTask(item.id)}
              className={`w-7 h-7 rounded-lg flex items-center justify-center shrink-0 mt-1 cursor-pointer transition-all ${
                item.completed
                  ? 'bg-emerald-500 text-slate-950 shadow-md shadow-emerald-500/30'
                  : 'bg-slate-950 border border-slate-700 text-slate-500 hover:border-emerald-500'
              }`}
            >
              {item.completed ? <CheckSquare className="w-4 h-4" /> : <Square className="w-4 h-4" />}
            </button>

            {/* Task Card */}
            <div className={`flex-1 p-5 rounded-2xl border transition-all ${
              item.completed
                ? 'bg-slate-950/40 border-slate-800/60 opacity-60'
                : 'bg-slate-950/80 border-slate-800 hover:border-slate-700'
            }`}>
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-bold text-emerald-400">{item.week}</span>
                  <span className={`text-[10px] px-2 py-0.5 rounded-full border font-semibold ${getCategoryBadge(item.category)}`}>
                    {item.category}
                  </span>
                </div>
                {item.priority === 'Urgent' && (
                  <span className="text-[10px] px-2 py-0.5 rounded-full bg-rose-500/20 text-rose-300 border border-rose-500/40 font-bold">
                    Urgent Task
                  </span>
                )}
              </div>

              <h3 className={`text-base font-bold text-slate-100 ${item.completed ? 'line-through' : ''}`}>
                {item.title}
              </h3>
              <p className="text-xs text-slate-400 leading-relaxed mt-1.5">{item.details}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
